apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matmul-results
  namespace: cmpm118
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 5Gi
